name: majorica
version: 1.0.1+1
publish_to: none
description: A new application for majorica marina hotel
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  animated_bottom_navigation_bar: ^0.3.2
  bdaya_custom_splash:
    git:
      url: https://github.com/Bdaya-Dev/custom-splash.git
      ref: master
  bdaya_fcm_handler: ^2.1.0
  bdaya_repository_pattern:
    git:
      url: git@github.com:AbdrahumanFikry/Flutter-Repository-Pattern.git
      ref: master
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  circular_countdown_timer: ^0.2.0
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  date_range_form_field: ^1.0.2
  dio: ^4.0.0
  fdottedline:
    git:
      url: git@github.com:t4ulabs/fdottedline.git
      ref: master
  file_picker: ^3.0.3
  firebase_analytics: ^8.2.0
  firebase_core: ^1.4.0
  firebase_crashlytics: ^2.1.1
  firebase_messaging: ^10.0.4
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.0.0+2
  flutter_secure_storage: ^4.2.0
  flutter_staggered_animations: ^1.0.0
  get: 4.2.4
  hive_flutter: ^1.1.0
  lottie: ^1.0.1
  percent_indicator: ^3.0.1
  photo_view: ^0.11.1
  pin_code_text_field: ^1.8.0
  share: ^2.0.4
  url_launcher: ^6.0.9
  webview_flutter: ^2.0.9


dev_dependencies:
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Black.ttf
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf
        - asset: assets/fonts/Cairo-Bold.ttf

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf





flutter_intl:
  enabled: true
  main_locale: ar
